# Generated by Django 6.0.3 on 2026-04-14 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='target_audience',
            field=models.CharField(choices=[('admin', 'Admin'), ('user', 'User'), ('both', 'Both')], default='user', max_length=10),
        ),
    ]
