# Generated by Django 6.0.3 on 2026-04-15 02:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_notification_target_audience'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='reservation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.reservation'),
        ),
    ]
