# Generated by Django 6.0.3 on 2026-04-16 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_notification_reservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='image',
            field=models.ImageField(blank=True, default='images/default.jpg', null=True, upload_to='facilities/'),
        ),
    ]
